import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CssBaseline from '@mui/material/CssBaseline'
import Navber from "./component/navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <CssBaseline />
        {children}
      </body>
    </html>
  );
}
